[theme]
primaryColor = "#007AFF"  # Apple's signature blue
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F5F5F7"  # Apple's light gray
textColor = "#1D1D1F"  # Apple's dark gray text
font = "SF Pro Display"  # Apple's system font

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"  # Minimal UI for cleaner look

[logger]
level = "info" 