[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
fastReruns = true
magicEnabled = true
installTracer = true
postScriptGC = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s" 